import argparse
import os
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl

# Use default matplotlib style rather than ggplot
mpl.style.use('default')

def plot_histograms(df, output_dir):
    """
    Generate histograms for chemical descriptors from the filtered CSV.
    """
    os.makedirs(output_dir, exist_ok=True)

    # These columns should exist in the CSV from the previous filter script
    # Adjust as needed if your CSV's column names differ.
    descriptors = [
        'MolecularWeight', 'HBA', 'HBD', 'TPSA',
        'RotatableBonds', 'DrugScore', 'LogP', 'NumAromaticRings'
    ]

    # Create a single figure with subplots for all histograms
    n_descriptors = len(descriptors)
    n_cols = 3  # Number of columns in the grid
    n_rows = (n_descriptors + n_cols - 1) // n_cols  # Calculate number of rows

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(15, 5 * n_rows), constrained_layout=True)
    axes = axes.flatten()

    for i, desc in enumerate(descriptors):
        if desc in df.columns:
            axes[i].hist(df[desc].dropna(), bins=50, alpha=0.75)
            axes[i].set_title(f"{desc} Distribution")
            axes[i].set_xlabel(desc)
            axes[i].set_ylabel("Count")

    # Remove empty subplots if the number of descriptors is less than the grid
    for j in range(i + 1, len(axes)):
        fig.delaxes(axes[j])

    # Save the combined figure
    combined_histogram_path = os.path.join(output_dir, "combined_histograms.png")
    plt.savefig(combined_histogram_path)
    plt.close()
    print("Combined histogram saved to:", combined_histogram_path)

def main():
    parser = argparse.ArgumentParser(
        description="Generate summary stats and histograms from filtered molecule CSV."
    )
    parser.add_argument(
        "--input_csv",
        required=True,
        help="Path to the CSV file generated by the previous filter script."
    )
    parser.add_argument(
        "--output_dir",
        required=True,
        help="Directory to save histogram plots and the descriptor summary."
    )
    args = parser.parse_args()

    # Read the CSV
    df = pd.read_csv(args.input_csv)

    # Print and save summary statistics
    print("\nDescriptor Summary:")
    print(df.describe())
    summary_path = os.path.join(args.output_dir, "descriptor_summary.csv")
    os.makedirs(args.output_dir, exist_ok=True)
    df.describe().to_csv(summary_path)
    print(f"\nSummary statistics saved to: {summary_path}")

    # Generate histograms for the main numeric columns
    plot_histograms(df, args.output_dir)

if __name__ == "__main__":
    main()
